package ui.Marketing;

/*
 *
 * Created on September 18, 2008, 2:54 PM
 */


import model.ProductManagement.ProductSummary;
import model.ProductManagement.Product;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Rushabh
 */
public class ViewProductDetailJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Product product;
    int revertFloor;
    int revertTarget;
    int revertCeli;
    public ViewProductDetailJPanel(JPanel userProcessContainer, Product product) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.product = product;
        this.revertFloor = product.getFloorPrice();
        this.revertTarget = product.getTargetPrice();
        this.revertCeli = product.getCeilingPrice();
        txtProdName.setText(product.toString());
        txtFloorPrice.setText(String.valueOf(product.getFloorPrice()));
        txtPrice.setText(String.valueOf(product.getTargetPrice()));
        txtCeliPrice.setText(String.valueOf(product.getCeilingPrice()));
        refresh();
        refreshAfter(false);
    }
    
    
    private void refresh(){
        lblActualSalesRevenueBefore.setText("Sales Revenue (Actual Price) : " + String.valueOf(product.getSalesVolume()));
        lblTargetSalesRevenueBefore.setText("Sales Revenue (Target Price) :" + String.valueOf(product.getSalesVolumeTarget()));
        lblPriceToPerformanceBefore.setText("Price to performance : " + String.valueOf(product.getOrderPricePerformance()));
        lblSalesAboveTargetBefore.setText("Number of sales above target : " + String.valueOf(product.getNumberOfProductSalesAboveTarget()));
        lblSalesBelowTargetBefore.setText("Number of sales below target : " + String.valueOf(product.getNumberOfProductSalesBelowTarget()));
    }
    
    private void refreshAfter(boolean simulateClicked){
        if (simulateClicked){
            lblActualSalesRevenueAfter.setText("Sales Revenue (Actual Price) : " + String.valueOf(product.getSalesVolume()));
            lblTargetSalesRevenueAfter.setText("Sales Revenue (Target Price) :" + String.valueOf(product.getSalesVolumeTarget()));
            lblPriceToPerformanceAfter.setText("Price to performance : " + String.valueOf(product.getOrderPricePerformance()));
            lblSalesAboveTargetAfter.setText("Number of sales above target : " + String.valueOf(product.getNumberOfProductSalesAboveTarget()));
            lblSalesBelowTargetAfter.setText("Number of sales below target : " + String.valueOf(product.getNumberOfProductSalesBelowTarget()));
        } else{
            lblActualSalesRevenueAfter.setText("Please click save and simulate to display");
            lblTargetSalesRevenueAfter.setText("");
            lblPriceToPerformanceAfter.setText("");
            lblSalesAboveTargetAfter.setText("");
            lblSalesBelowTargetAfter.setText("");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        backButton1 = new javax.swing.JButton();
        txtFloorPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCeliPrice = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        BusinessIntelligenceJPanel = new javax.swing.JPanel();
        lblBusinessIntelligence = new javax.swing.JLabel();
        lblActualSalesRevenueBefore = new javax.swing.JLabel();
        lblSalesBelowTargetBefore = new javax.swing.JLabel();
        lblSalesAboveTargetBefore = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPriceToPerformanceBefore = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblActualSalesRevenueAfter = new javax.swing.JLabel();
        lblPriceToPerformanceAfter = new javax.swing.JLabel();
        lblSalesAboveTargetAfter = new javax.swing.JLabel();
        lblSalesBelowTargetAfter = new javax.swing.JLabel();
        lblBefore = new javax.swing.JLabel();
        lblAfter = new javax.swing.JLabel();
        lblTargetSalesRevenueBefore = new javax.swing.JLabel();
        lblTargetSalesRevenueAfter = new javax.swing.JLabel();
        btnRevert = new javax.swing.JButton();
        btnAutomatedSimulate = new javax.swing.JButton();

        setBackground(new java.awt.Color(47, 73, 97));
        setPreferredSize(new java.awt.Dimension(650, 600));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Details");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name:");

        txtProdName.setBackground(new java.awt.Color(66, 103, 138));
        txtProdName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Target Price:");

        txtPrice.setBackground(new java.awt.Color(66, 103, 138));
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));

        backButton1.setBackground(new java.awt.Color(123, 192, 255));
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        txtFloorPrice.setBackground(new java.awt.Color(66, 103, 138));
        txtFloorPrice.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Floor Price");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ceil Price:");

        txtCeliPrice.setBackground(new java.awt.Color(66, 103, 138));
        txtCeliPrice.setForeground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(123, 192, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        BusinessIntelligenceJPanel.setBackground(new java.awt.Color(105, 164, 219));
        BusinessIntelligenceJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BusinessIntelligenceJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusinessIntelligenceJPanelMouseClicked(evt);
            }
        });

        lblBusinessIntelligence.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblBusinessIntelligence.setText("Product Performance Report");

        lblActualSalesRevenueBefore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblActualSalesRevenueBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualSalesRevenueBefore.setText("Sales Revenue (Actual Price) :");

        lblSalesBelowTargetBefore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSalesBelowTargetBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalesBelowTargetBefore.setText("Number of sales below target :");

        lblSalesAboveTargetBefore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSalesAboveTargetBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalesAboveTargetBefore.setText("Number of sales above target :");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        lblPriceToPerformanceBefore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblPriceToPerformanceBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceToPerformanceBefore.setText("Price to performance :");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblActualSalesRevenueAfter.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblActualSalesRevenueAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualSalesRevenueAfter.setText("Sales Revenue (Actual Price) :");

        lblPriceToPerformanceAfter.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblPriceToPerformanceAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceToPerformanceAfter.setText("Price to performance :");

        lblSalesAboveTargetAfter.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSalesAboveTargetAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalesAboveTargetAfter.setText("Number of sales above target :");

        lblSalesBelowTargetAfter.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSalesBelowTargetAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalesBelowTargetAfter.setText("Number of sales below target :");

        lblBefore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBefore.setText("Before");

        lblAfter.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAfter.setText("After");

        lblTargetSalesRevenueBefore.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTargetSalesRevenueBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTargetSalesRevenueBefore.setText("Sales Revenue (Target Price) :");

        lblTargetSalesRevenueAfter.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTargetSalesRevenueAfter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTargetSalesRevenueAfter.setText("Sales Revenue (Target Price) :");

        javax.swing.GroupLayout BusinessIntelligenceJPanelLayout = new javax.swing.GroupLayout(BusinessIntelligenceJPanel);
        BusinessIntelligenceJPanel.setLayout(BusinessIntelligenceJPanelLayout);
        BusinessIntelligenceJPanelLayout.setHorizontalGroup(
            BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(BusinessIntelligenceJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBusinessIntelligence)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BusinessIntelligenceJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActualSalesRevenueBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTargetSalesRevenueBefore)
                    .addComponent(lblSalesAboveTargetBefore)
                    .addComponent(lblSalesBelowTargetBefore)
                    .addComponent(lblPriceToPerformanceBefore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAfter)
                    .addComponent(lblActualSalesRevenueAfter)
                    .addComponent(lblTargetSalesRevenueAfter)
                    .addComponent(lblPriceToPerformanceAfter)
                    .addComponent(lblSalesBelowTargetAfter)
                    .addComponent(lblSalesAboveTargetAfter))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BusinessIntelligenceJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblActualSalesRevenueAfter, lblActualSalesRevenueBefore, lblPriceToPerformanceAfter, lblPriceToPerformanceBefore, lblSalesAboveTargetAfter, lblSalesAboveTargetBefore, lblSalesBelowTargetAfter, lblSalesBelowTargetBefore, lblTargetSalesRevenueAfter, lblTargetSalesRevenueBefore});

        BusinessIntelligenceJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAfter, lblBefore});

        BusinessIntelligenceJPanelLayout.setVerticalGroup(
            BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusinessIntelligenceJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBusinessIntelligence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BusinessIntelligenceJPanelLayout.createSequentialGroup()
                        .addGroup(BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBefore)
                            .addComponent(lblAfter))
                        .addGap(18, 18, 18)
                        .addGroup(BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblActualSalesRevenueBefore)
                            .addComponent(lblActualSalesRevenueAfter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTargetSalesRevenueBefore)
                            .addComponent(lblTargetSalesRevenueAfter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BusinessIntelligenceJPanelLayout.createSequentialGroup()
                                .addComponent(lblPriceToPerformanceAfter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSalesAboveTargetAfter))
                            .addGroup(BusinessIntelligenceJPanelLayout.createSequentialGroup()
                                .addComponent(lblPriceToPerformanceBefore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSalesAboveTargetBefore)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BusinessIntelligenceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalesBelowTargetAfter)
                            .addComponent(lblSalesBelowTargetBefore)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnRevert.setBackground(new java.awt.Color(123, 192, 255));
        btnRevert.setText("Revert");
        btnRevert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevertActionPerformed(evt);
            }
        });

        btnAutomatedSimulate.setBackground(new java.awt.Color(123, 192, 255));
        btnAutomatedSimulate.setText("Auto Simulate");
        btnAutomatedSimulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomatedSimulateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCeliPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnRevert)
                        .addGap(18, 18, 18)
                        .addComponent(btnAutomatedSimulate)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(BusinessIntelligenceJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCeliPrice, txtFloorPrice, txtPrice, txtProdName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCeliPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnRevert)
                    .addComponent(btnAutomatedSimulate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(BusinessIntelligenceJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MarketingWorkAreaJPanel mwajp = (MarketingWorkAreaJPanel) component;
        mwajp.populateProductTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String productName = txtProdName.getText();
        if (productName.isBlank()){
            JOptionPane.showMessageDialog(this, "Product name cannot be blank", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int floorPrice;
        int ceilPrice;
        int targetPrice;
        try{
            floorPrice = Integer.parseInt(txtFloorPrice.getText());
            ceilPrice = Integer.parseInt(txtCeliPrice.getText());
            targetPrice = Integer.parseInt(txtPrice.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Check pricing fields floor, ceiling and target.", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ((floorPrice <= targetPrice) && (targetPrice <= ceilPrice)) {
            product.setName(productName);
            product.updateProduct(floorPrice, ceilPrice, targetPrice);
            refreshAfter(true);
        }else{
            JOptionPane.showMessageDialog(this, "Target price should be between floor price and ceiling price.", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void BusinessIntelligenceJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusinessIntelligenceJPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BusinessIntelligenceJPanelMouseClicked

    private void btnRevertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevertActionPerformed
        // TODO add your handling code here:
        txtFloorPrice.setText(String.valueOf(this.revertFloor));
        txtPrice.setText(String.valueOf(this.revertTarget));
        txtCeliPrice.setText(String.valueOf(this.revertCeli));
        product.updateProduct(this.revertFloor, this.revertCeli, this.revertTarget);
        refresh();
        refreshAfter(false);
    }//GEN-LAST:event_btnRevertActionPerformed

    private void btnAutomatedSimulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomatedSimulateActionPerformed
        int previousPricePerformance = product.getOrderPricePerformance();
        this.revertFloor = product.getFloorPrice();
        this.revertTarget = product.getTargetPrice();
        this.revertCeli = product.getCeilingPrice();
        int bestTarget = this.revertTarget;
        if (previousPricePerformance > 0){
            product.updateProduct(this.revertFloor, this.revertCeli, bestTarget + 1);
            int currentPricePerformance = product.getOrderPricePerformance();
            while(currentPricePerformance >= 0 && bestTarget < this.revertCeli){
                bestTarget += 1;
                product.updateProduct(this.revertFloor, this.revertCeli, bestTarget + 1);
                currentPricePerformance = product.getOrderPricePerformance();
            }
        } else {
            product.updateProduct(this.revertFloor, this.revertCeli, bestTarget - 1);
            int currentPricePerformance = product.getOrderPricePerformance();
            while(currentPricePerformance < 50 && bestTarget > this.revertFloor){
                bestTarget -= 1;
                product.updateProduct(this.revertFloor, this.revertCeli, bestTarget - 1);
                currentPricePerformance = product.getOrderPricePerformance();
            }
        }
        product.updateProduct(this.revertFloor, this.revertCeli, bestTarget);
        txtPrice.setText(String.valueOf(bestTarget));
        refreshAfter(true);
    }//GEN-LAST:event_btnAutomatedSimulateActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BusinessIntelligenceJPanel;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton btnAutomatedSimulate;
    private javax.swing.JButton btnRevert;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblActualSalesRevenueAfter;
    private javax.swing.JLabel lblActualSalesRevenueBefore;
    private javax.swing.JLabel lblAfter;
    private javax.swing.JLabel lblBefore;
    private javax.swing.JLabel lblBusinessIntelligence;
    private javax.swing.JLabel lblPriceToPerformanceAfter;
    private javax.swing.JLabel lblPriceToPerformanceBefore;
    private javax.swing.JLabel lblSalesAboveTargetAfter;
    private javax.swing.JLabel lblSalesAboveTargetBefore;
    private javax.swing.JLabel lblSalesBelowTargetAfter;
    private javax.swing.JLabel lblSalesBelowTargetBefore;
    private javax.swing.JLabel lblTargetSalesRevenueAfter;
    private javax.swing.JLabel lblTargetSalesRevenueBefore;
    private javax.swing.JTextField txtCeliPrice;
    private javax.swing.JTextField txtFloorPrice;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProdName;
    // End of variables declaration//GEN-END:variables
    
}
